### ISSUE TITLE
Use streaming to make import more memory efficient

### ISSUE THREAD

**Issue by benradf** [tweag/skyscope#59]
Currently the whole graph is loaded into memory before being written to a Sqlite database. This was convenient for prototyping but it can cause the import process to get OOM killed when importing large Skyframe graphs. For example:
```
INFO: Running command line: bazel-bin/external/skyscope_linux/skyscope/import.sh '--query=//envoy/server:all' '--aquery=//envoy/server:all'
importing skyframe
/home/ben/.cache/bazel/_bazel_ben/478f2e6872fa39b610e38c9534d50752/execroot/envoy/bazel-out/k8-fastbuild/bin/external/skyscope_linux/skyscope/import.sh.runfiles/envoy/../skyscope_linux/skyscope/skyscope: line 3:
892287 Killed                  LD_LIBRARY_PATH="$RUNFILES/external/skyscope_linux/skyscope/closure" "$RUNFILES/external/skyscope_linux/skyscope/closure/skyscope" "$@"
```

Instead, each part of the import pipeline should process and emit chunks of data (e.g. parser consumes lines and emits nodes and edges). Additionally, this would also be a good opportunity to consider rewriting the import process in C++ for maximum performance.

**Comment by layus** [comment]
Just crashed with 30 GB of ram + 15GB of swap :cry:

**Comment by layus** [comment]
There is a dire need for this feature, as the numbers are really out of hand. I have tried to import-skyframe a bazel dump of about 2.5GiB, and the process crashed after consuming > 100GiB of memory+swap. Meaning that the haskell process needs >40x it's input size, assuming that relation is linear, which it may not be.

![image](https://github.com/tweag/skyscope/assets/632767/945e2f76-b6b1-485a-acd9-07e60430ede9)

**Comment by layus** [comment]
How can I help ? Is there any documentation on the format ?

**Comment by benradf** [comment]
Sorry for the delayed reply. Took me a little while to context switch back to back to this issue :slightly_smiling_face:

I've been in two minds about how to go about resolving it for a while:
1. Fix the space leak (possibly using [conduit](https://hackage.haskell.org/package/conduit) or another streaming library).
    **Pro:** Get to keep using Haskell for import code. Parser combinators are preferable to ad-hoc parsing.
    **Con:** Difficult to estimate how long this would take. Chasing down space leaks in Haskell is not easy.
2. Rewrite the importer in C++.
    **Pro:** Much easier to write a fast importer which uses minimal resources. Easy to profile and speed up further.
    **Con:** Language is far less pleasant to work in. Parser will not be trivially extensible.

As much as I prefer working in Haskell, I'm leaning toward _2. Rewrite the importer in C++_. I had an old branch where I started prototyping this a month ago, so I spent yesterday [getting it into shape](https://github.com/tweag/skyscope/pull/95).

It's not finished, but it is now able to import from Bazel 5. Remaining tasks include:
- Test this against large repositories that previously made the tool crash.
- Implement parser for Bazel 6 Skyframe format.
- Fix newly introduced GHCi linker error:
  `libimport.so: undefined symbol: sqlite3_initialize`
  A full build works fine, only GHCi encounters this.
- Possibly other stuff I've not thought of yet.

If you want to help with any of that, I'm happy to have a pairing session to get started.

**Comment by benradf** [comment]
> Is there any documentation on the format ?

Unfortunately no. At least I never found anything.

I think this is deliberate as the `bazel dump --skyframe` is not meant to be an official interface you can depend on.

Still, the format is fairly self explanatory. I added a couple of comments with details:
- https://github.com/tweag/skyscope/pull/95/files#r1226386455
- https://github.com/tweag/skyscope/pull/95/files#r1226389756

Note that while the Skyframe dump looks quite intimidating initially, we don't need to fully parse it. Node keys are mostly treated as opaque blobs, separated by `|` characters (or `\n` in Bazel 6). A hash of the node key is what is used to actually identity the node.
