### ISSUE TITLE
skyscope_linux/skyscope/import: line 4: /bin/skyscope: No such file or directory

### ISSUE THREAD

**Issue by Strum355** [tweag/skyscope#85]
**Describe the bug**
Running skyscope on https://github.com/sourcegraph/sourcegraph after running `bazel build //cmd/gitserver` 

**To Reproduce**

Append to `WORKSPACE`:
```python
http_archive(
    name = "skyscope",
    sha256 = "2acf7b7f5bf3e66b83e1fac3aa6bcf71d173433ca6786f83d62fb5e9241fe7dc",
    urls = ["https://github.com/tweag/skyscope/releases/download/v0.2.6/skyscope.zip"],
)

load("@skyscope//:repository.bzl", "configure_skyscope")

configure_skyscope()
```

Run `bazel shutdown && bazel build //cmd/gitserver && bazel run -- @skyscope//:import`

**Expected behavior**
It works I guess :sweat_smile: 

**Environment**
 - OS name + version: NixOS using bazel (6.1.2) from the repos devshell
 - Version of the code: 0.2.6

**Additional context**
Output with SKYSCOPE_DEBUG set:
```
$ SKYSCOPE_DEBUG=1 bazel run -- @skyscope//:import
INFO: Build option --action_env has changed, discarding analysis cache.
INFO: Analyzed target @skyscope//:import (93 packages loaded, 350 targets configured).
INFO: Found 1 target...
Target @skyscope_linux//skyscope:import up-to-date:
  bazel-bin/external/skyscope_linux/skyscope/import
INFO: Elapsed time: 0.316s, Critical Path: 0.00s
INFO: 2 processes: 2 internal.
INFO: Build completed successfully, 2 total actions
INFO: Running command line: bazel-bin/external/skyscope_linux/skyscope/import
+++ find . -type d -name skyscope -printf '/home/noah/.cache/bazel/_bazel_noah/8fd1d20666a46767e7f29541678514a0/execroot/__main__/bazel-out/k8-fastbuild/bin/external/skyscope_linux/skyscope/import.runfiles/__main__/%P\n' -quit
++ RELEASE_DIR=
++ export SKYSCOPE_BINARY=/closure/skyscope
++ SKYSCOPE_BINARY=/closure/skyscope
++ /bin/skyscope import
/home/noah/.cache/bazel/_bazel_noah/8fd1d20666a46767e7f29541678514a0/execroot/__main__/bazel-out/k8-fastbuild/bin/external/skyscope_linux/skyscope/import: line 4: /bin/skyscope: No such file or directory
```

**Comment by Strum355** [comment]
Thanks for the response! Curious what the diff was for getting devshell and bazel to work, it was a lot of work to get things working in the first place so itd be very interested to know what fell through the gaps (always good to have a fresh uncached system trying it out 😅)

**Comment by Strum355** [comment]
> It looks like the interpreter for that cargo binary isn't right for NixOS:

Thats weird, we're specifically using rust toolchain from rules_nixpkgs when the host is nixos for this reason 🤔 wonder is the order of when we load them the issue here, i may have only tested when we configured the toolchain before calling crates_index, but I digress. 
Thanks for the fix, will test asap!

**Comment by benradf** [comment]
Should be resolved now that Skyscope is distributed as a [single statically linked binary](https://github.com/tweag/skyscope/pull/94).
