### ISSUE TITLE
General Purpose Scope

### ISSUE THREAD

**Issue by dwincort** [tweag/skyscope#91]
I read your article at https://www.tweag.io/blog/2023-05-04-announcing-skyscope/, and I find the user interface you designed really convenient.  I too have a bunch of data in the form of a labeled DAG, and as with Skyframe data, it's too much for graphviz to handle at once (and even if it could, it would be too difficult to read and understand).  I would love to use the system you've made to visualize this data.  Do you think this is possible, and can you describe how this might be done?

I'm imagining there may be some way for me to represent my data _as_ a skyframe build graph so that I could then import it into skyscope.  Do you have any tips on that?  Also, I guess I would need to set up skyscope in some sort of empty bazel project?  I'm not sure how to do that.

I guess, to make this a proper feature request, I'm asking for:
- A README describing how to use skyscope for non-skyframe data that also represents a dependency graph including:
  - How to start up skyscope so that it does not suck up skyframe information from bazel
  - What features need to be present in the input data for skyscope to work properly
- (and, if necessary, additional interface options to support such a use case)

**Comment by benradf** [comment]
Thanks for opening this issue — I definitely see potential for the tool to be used to visualise more than just Skyframe graphs, and your interest encouraged me to quickly hack something together this morning. I don't have time to productionise it at the moment, but you should be able to checkout [this branch](https://github.com/tweag/skyscope/pull/92) and try it yourself.

The change adds a new `import-json` command to `skyscope` that you can use like this:

```bash
bazel run -- //:skyscope import-json <graph.json
```

Where `graph.json` looks something like:

```json
[
  {
    "hash1": {
      "nodeData": "data1",
      "nodeType": "type1"
    },
    "hash2": {
      "nodeData": "data2",
      "nodeType": "type2"
    }
  },
  [
    {
      "edgeGroup": 0,
      "edgeSource": "hash1",
      "edgeTarget": "hash2"
    }
  ]
]
```

The format is just the Aeson serialisation of [Graph](https://github.com/tweag/skyscope/blob/37967c7741012db89a10594a8a273ab84240da6d/backend/src/Model.hs#L39) (i.e. a pair of node map and edge list). As an example of how this might be used, I added a [script](https://github.com/tweag/skyscope/blob/37967c7741012db89a10594a8a273ab84240da6d/import-process-tree.sh) which imports a snapshot of the process tree from `ps`. Note that the hashes just need to be unique node identifiers, not necessarily actual hash values (for the `ps` example they are just PIDs).

![image](https://github.com/tweag/skyscope/assets/104896700/eab2728c-fe8c-4e7c-b355-a5ea075257d0)

Let me know if you have any problems or questions about this new mode.

**Comment by dwincort** [comment]
Hi again,

Thank you so much for putting this together.  I really do think it would have been great for me, but in a wild case of bad timing, the project I was working on got scrapped yesterday.

**Comment by benradf** [comment]
> in a wild case of bad timing, the project I was working on got scrapped yesterday.

Ah, I'm sorry to hear that.

I think this is a useful feature for the tool to have though, so the effort isn't wasted. Thanks again for the request :slightly_smiling_face:

**Comment by benradf** [comment]
Skyscope [now supports](https://github.com/tweag/skyscope#general-purpose-use) importing arbitrary Graphviz graphs.
